type Good {
  _id: ID
  title: String!
  count: Int!
  cost: Float
  isDisabled: Boolean
}

type Query {
  getGoods: [Good]
}

type Mutation {
  addGood(title: String!, count: Int!, cost: Float, isDisabled: Boolean): Good!
}
